/*
 * Copyright (C) Telecom SudParis
 * See LICENSE in top-level directory.
 */

#ifndef OTF2_H
#define OTF2_H

/**
 *  @file
 *
 *  @brief      Main include file for applications using OTF2.
 */

#include <otf2/OTF2_Reader.h>
//#include <otf2/otf2_compiler.h>

#ifndef __otf2_deprecated__
#define __otf2_deprecated__
#endif

#include "pallas/pallas.h"
#include "pallas/pallas_archive.h"
#include "pallas/pallas_write.h"
#include "pallas/pallas_read.h"

struct OTF2_GlobalDefWriter_struct {
  struct GlobalArchive * archive;
};

struct OTF2_DefWriter_struct {
  OTF2_LocationRef locationRef;
  struct Archive* archive;

  struct ThreadWriter* thread_writer;
};

struct OTF2_EvtWriter_struct {
  OTF2_LocationRef locationRef;
  struct Archive* archive;
  struct ThreadWriter* thread_writer;
};

struct OTF2_Archive_struct {
  struct Archive* archive;

  OTF2_GlobalDefWriter* globalDefWriter;

  OTF2_DefWriter** def_writers;
  OTF2_EvtWriter** evt_writers;
  int nb_locations;

  struct OTF2_LockingCallbacks lockingCallbacks;
  void* lockingData;

  struct OTF2_FlushCallbacks flushCallbacks;
  void* flushData;

  pthread_mutex_t lock;
};


struct OTF2_GlobalDefReaderCallbacks_struct {
  OTF2_GlobalDefReaderCallback_Unknown OTF2_GlobalDefReaderCallback_Unknown_callback;
  OTF2_GlobalDefReaderCallback_ClockProperties OTF2_GlobalDefReaderCallback_ClockProperties_callback;
  OTF2_GlobalDefReaderCallback_Paradigm OTF2_GlobalDefReaderCallback_Paradigm_callback;
  OTF2_GlobalDefReaderCallback_ParadigmProperty OTF2_GlobalDefReaderCallback_ParadigmProperty_callback;
  OTF2_GlobalDefReaderCallback_IoParadigm OTF2_GlobalDefReaderCallback_IoParadigm_callback;
  OTF2_GlobalDefReaderCallback_String OTF2_GlobalDefReaderCallback_String_callback;
  OTF2_GlobalDefReaderCallback_Attribute OTF2_GlobalDefReaderCallback_Attribute_callback;
  OTF2_GlobalDefReaderCallback_SystemTreeNode OTF2_GlobalDefReaderCallback_SystemTreeNode_callback;
  OTF2_GlobalDefReaderCallback_LocationGroup OTF2_GlobalDefReaderCallback_LocationGroup_callback;
  OTF2_GlobalDefReaderCallback_Location OTF2_GlobalDefReaderCallback_Location_callback;
  OTF2_GlobalDefReaderCallback_Region OTF2_GlobalDefReaderCallback_Region_callback;
  OTF2_GlobalDefReaderCallback_Callsite OTF2_GlobalDefReaderCallback_Callsite_callback;
  OTF2_GlobalDefReaderCallback_Callpath OTF2_GlobalDefReaderCallback_Callpath_callback;
  OTF2_GlobalDefReaderCallback_Group OTF2_GlobalDefReaderCallback_Group_callback;
  OTF2_GlobalDefReaderCallback_MetricMember OTF2_GlobalDefReaderCallback_MetricMember_callback;
  OTF2_GlobalDefReaderCallback_MetricClass OTF2_GlobalDefReaderCallback_MetricClass_callback;
  OTF2_GlobalDefReaderCallback_MetricInstance OTF2_GlobalDefReaderCallback_MetricInstance_callback;
  OTF2_GlobalDefReaderCallback_Comm OTF2_GlobalDefReaderCallback_Comm_callback;
  OTF2_GlobalDefReaderCallback_Parameter OTF2_GlobalDefReaderCallback_Parameter_callback;
  OTF2_GlobalDefReaderCallback_RmaWin OTF2_GlobalDefReaderCallback_RmaWin_callback;
  OTF2_GlobalDefReaderCallback_MetricClassRecorder OTF2_GlobalDefReaderCallback_MetricClassRecorder_callback;
  OTF2_GlobalDefReaderCallback_SystemTreeNodeProperty OTF2_GlobalDefReaderCallback_SystemTreeNodeProperty_callback;
  OTF2_GlobalDefReaderCallback_SystemTreeNodeDomain OTF2_GlobalDefReaderCallback_SystemTreeNodeDomain_callback;
  OTF2_GlobalDefReaderCallback_LocationGroupProperty OTF2_GlobalDefReaderCallback_LocationGroupProperty_callback;
  OTF2_GlobalDefReaderCallback_LocationProperty OTF2_GlobalDefReaderCallback_LocationProperty_callback;
  OTF2_GlobalDefReaderCallback_CartDimension OTF2_GlobalDefReaderCallback_CartDimension_callback;
  OTF2_GlobalDefReaderCallback_CartTopology OTF2_GlobalDefReaderCallback_CartTopology_callback;
  OTF2_GlobalDefReaderCallback_CartCoordinate OTF2_GlobalDefReaderCallback_CartCoordinate_callback;
  OTF2_GlobalDefReaderCallback_SourceCodeLocation OTF2_GlobalDefReaderCallback_SourceCodeLocation_callback;
  OTF2_GlobalDefReaderCallback_CallingContext OTF2_GlobalDefReaderCallback_CallingContext_callback;
  OTF2_GlobalDefReaderCallback_CallingContextProperty OTF2_GlobalDefReaderCallback_CallingContextProperty_callback;
  OTF2_GlobalDefReaderCallback_InterruptGenerator OTF2_GlobalDefReaderCallback_InterruptGenerator_callback;
  OTF2_GlobalDefReaderCallback_IoFileProperty OTF2_GlobalDefReaderCallback_IoFileProperty_callback;
  OTF2_GlobalDefReaderCallback_IoRegularFile OTF2_GlobalDefReaderCallback_IoRegularFile_callback;
  OTF2_GlobalDefReaderCallback_IoDirectory OTF2_GlobalDefReaderCallback_IoDirectory_callback;
  OTF2_GlobalDefReaderCallback_IoHandle OTF2_GlobalDefReaderCallback_IoHandle_callback;
  OTF2_GlobalDefReaderCallback_IoPreCreatedHandleState OTF2_GlobalDefReaderCallback_IoPreCreatedHandleState_callback;
  OTF2_GlobalDefReaderCallback_CallpathParameter OTF2_GlobalDefReaderCallback_CallpathParameter_callback;
  OTF2_GlobalDefReaderCallback_InterComm OTF2_GlobalDefReaderCallback_InterComm_callback;
};

struct OTF2_GlobalDefReader_struct {
  struct GlobalArchive *archive;

  OTF2_GlobalDefReaderCallbacks callbacks;
  void* user_data;
};

struct OTF2_DefReader_struct {
  OTF2_LocationRef location;
  PALLAS(ThreadReader)* thread_reader;

  OTF2_DefReaderCallbacks callbacks;
  void* user_data;
};

struct OTF2_EvtReader_struct {
  OTF2_LocationRef location;
  PALLAS(ThreadReader) * thread_reader;
};

struct OTF2_GlobalEvtReaderCallbacks_struct {
  OTF2_GlobalEvtReaderCallback_Unknown OTF2_GlobalEvtReaderCallback_Unknown_callback;
  OTF2_GlobalEvtReaderCallback_BufferFlush OTF2_GlobalEvtReaderCallback_BufferFlush_callback;
  OTF2_GlobalEvtReaderCallback_MeasurementOnOff OTF2_GlobalEvtReaderCallback_MeasurementOnOff_callback;
  OTF2_GlobalEvtReaderCallback_Enter OTF2_GlobalEvtReaderCallback_Enter_callback;
  OTF2_GlobalEvtReaderCallback_Leave OTF2_GlobalEvtReaderCallback_Leave_callback;
  OTF2_GlobalEvtReaderCallback_MpiSend OTF2_GlobalEvtReaderCallback_MpiSend_callback;
  OTF2_GlobalEvtReaderCallback_MpiIsend OTF2_GlobalEvtReaderCallback_MpiIsend_callback;
  OTF2_GlobalEvtReaderCallback_MpiIsendComplete OTF2_GlobalEvtReaderCallback_MpiIsendComplete_callback;
  OTF2_GlobalEvtReaderCallback_MpiIrecvRequest OTF2_GlobalEvtReaderCallback_MpiIrecvRequest_callback;
  OTF2_GlobalEvtReaderCallback_MpiRecv OTF2_GlobalEvtReaderCallback_MpiRecv_callback;
  OTF2_GlobalEvtReaderCallback_MpiIrecv OTF2_GlobalEvtReaderCallback_MpiIrecv_callback;
  OTF2_GlobalEvtReaderCallback_MpiRequestTest OTF2_GlobalEvtReaderCallback_MpiRequestTest_callback;
  OTF2_GlobalEvtReaderCallback_MpiRequestCancelled OTF2_GlobalEvtReaderCallback_MpiRequestCancelled_callback;
  OTF2_GlobalEvtReaderCallback_MpiCollectiveBegin OTF2_GlobalEvtReaderCallback_MpiCollectiveBegin_callback;
  OTF2_GlobalEvtReaderCallback_MpiCollectiveEnd OTF2_GlobalEvtReaderCallback_MpiCollectiveEnd_callback;
  OTF2_GlobalEvtReaderCallback_OmpFork OTF2_GlobalEvtReaderCallback_OmpFork_callback;
  OTF2_GlobalEvtReaderCallback_OmpJoin OTF2_GlobalEvtReaderCallback_OmpJoin_callback;
  OTF2_GlobalEvtReaderCallback_OmpAcquireLock OTF2_GlobalEvtReaderCallback_OmpAcquireLock_callback;
  OTF2_GlobalEvtReaderCallback_OmpReleaseLock OTF2_GlobalEvtReaderCallback_OmpReleaseLock_callback;
  OTF2_GlobalEvtReaderCallback_OmpTaskCreate OTF2_GlobalEvtReaderCallback_OmpTaskCreate_callback;
  OTF2_GlobalEvtReaderCallback_OmpTaskSwitch OTF2_GlobalEvtReaderCallback_OmpTaskSwitch_callback;
  OTF2_GlobalEvtReaderCallback_OmpTaskComplete OTF2_GlobalEvtReaderCallback_OmpTaskComplete_callback;
  OTF2_GlobalEvtReaderCallback_Metric OTF2_GlobalEvtReaderCallback_Metric_callback;
  OTF2_GlobalEvtReaderCallback_ParameterString OTF2_GlobalEvtReaderCallback_ParameterString_callback;
  OTF2_GlobalEvtReaderCallback_ParameterInt OTF2_GlobalEvtReaderCallback_ParameterInt_callback;
  OTF2_GlobalEvtReaderCallback_ParameterUnsignedInt OTF2_GlobalEvtReaderCallback_ParameterUnsignedInt_callback;
  OTF2_GlobalEvtReaderCallback_RmaWinCreate OTF2_GlobalEvtReaderCallback_RmaWinCreate_callback;
  OTF2_GlobalEvtReaderCallback_RmaWinDestroy OTF2_GlobalEvtReaderCallback_RmaWinDestroy_callback;
  OTF2_GlobalEvtReaderCallback_RmaCollectiveBegin OTF2_GlobalEvtReaderCallback_RmaCollectiveBegin_callback;
  OTF2_GlobalEvtReaderCallback_RmaCollectiveEnd OTF2_GlobalEvtReaderCallback_RmaCollectiveEnd_callback;
  OTF2_GlobalEvtReaderCallback_RmaGroupSync OTF2_GlobalEvtReaderCallback_RmaGroupSync_callback;
  OTF2_GlobalEvtReaderCallback_RmaRequestLock OTF2_GlobalEvtReaderCallback_RmaRequestLock_callback;
  OTF2_GlobalEvtReaderCallback_RmaAcquireLock OTF2_GlobalEvtReaderCallback_RmaAcquireLock_callback;
  OTF2_GlobalEvtReaderCallback_RmaTryLock OTF2_GlobalEvtReaderCallback_RmaTryLock_callback;
  OTF2_GlobalEvtReaderCallback_RmaReleaseLock OTF2_GlobalEvtReaderCallback_RmaReleaseLock_callback;
  OTF2_GlobalEvtReaderCallback_RmaSync OTF2_GlobalEvtReaderCallback_RmaSync_callback;
  OTF2_GlobalEvtReaderCallback_RmaWaitChange OTF2_GlobalEvtReaderCallback_RmaWaitChange_callback;
  OTF2_GlobalEvtReaderCallback_RmaPut OTF2_GlobalEvtReaderCallback_RmaPut_callback;
  OTF2_GlobalEvtReaderCallback_RmaGet OTF2_GlobalEvtReaderCallback_RmaGet_callback;
  OTF2_GlobalEvtReaderCallback_RmaAtomic OTF2_GlobalEvtReaderCallback_RmaAtomic_callback;
  OTF2_GlobalEvtReaderCallback_RmaOpCompleteBlocking OTF2_GlobalEvtReaderCallback_RmaOpCompleteBlocking_callback;
  OTF2_GlobalEvtReaderCallback_RmaOpCompleteNonBlocking OTF2_GlobalEvtReaderCallback_RmaOpCompleteNonBlocking_callback;
  OTF2_GlobalEvtReaderCallback_RmaOpTest OTF2_GlobalEvtReaderCallback_RmaOpTest_callback;
  OTF2_GlobalEvtReaderCallback_RmaOpCompleteRemote OTF2_GlobalEvtReaderCallback_RmaOpCompleteRemote_callback;
  OTF2_GlobalEvtReaderCallback_ThreadFork OTF2_GlobalEvtReaderCallback_ThreadFork_callback;
  OTF2_GlobalEvtReaderCallback_ThreadJoin OTF2_GlobalEvtReaderCallback_ThreadJoin_callback;
  OTF2_GlobalEvtReaderCallback_ThreadTeamBegin OTF2_GlobalEvtReaderCallback_ThreadTeamBegin_callback;
  OTF2_GlobalEvtReaderCallback_ThreadTeamEnd OTF2_GlobalEvtReaderCallback_ThreadTeamEnd_callback;
  OTF2_GlobalEvtReaderCallback_ThreadAcquireLock OTF2_GlobalEvtReaderCallback_ThreadAcquireLock_callback;
  OTF2_GlobalEvtReaderCallback_ThreadReleaseLock OTF2_GlobalEvtReaderCallback_ThreadReleaseLock_callback;
  OTF2_GlobalEvtReaderCallback_ThreadTaskCreate OTF2_GlobalEvtReaderCallback_ThreadTaskCreate_callback;
  OTF2_GlobalEvtReaderCallback_ThreadTaskSwitch OTF2_GlobalEvtReaderCallback_ThreadTaskSwitch_callback;
  OTF2_GlobalEvtReaderCallback_ThreadTaskComplete OTF2_GlobalEvtReaderCallback_ThreadTaskComplete_callback;
  OTF2_GlobalEvtReaderCallback_ThreadCreate OTF2_GlobalEvtReaderCallback_ThreadCreate_callback;
  OTF2_GlobalEvtReaderCallback_ThreadBegin OTF2_GlobalEvtReaderCallback_ThreadBegin_callback;
  OTF2_GlobalEvtReaderCallback_ThreadWait OTF2_GlobalEvtReaderCallback_ThreadWait_callback;
  OTF2_GlobalEvtReaderCallback_ThreadEnd OTF2_GlobalEvtReaderCallback_ThreadEnd_callback;
  OTF2_GlobalEvtReaderCallback_CallingContextEnter OTF2_GlobalEvtReaderCallback_CallingContextEnter_callback;
  OTF2_GlobalEvtReaderCallback_CallingContextLeave OTF2_GlobalEvtReaderCallback_CallingContextLeave_callback;
  OTF2_GlobalEvtReaderCallback_CallingContextSample OTF2_GlobalEvtReaderCallback_CallingContextSample_callback;
  OTF2_GlobalEvtReaderCallback_IoCreateHandle OTF2_GlobalEvtReaderCallback_IoCreateHandle_callback;
  OTF2_GlobalEvtReaderCallback_IoDestroyHandle OTF2_GlobalEvtReaderCallback_IoDestroyHandle_callback;
  OTF2_GlobalEvtReaderCallback_IoDuplicateHandle OTF2_GlobalEvtReaderCallback_IoDuplicateHandle_callback;
  OTF2_GlobalEvtReaderCallback_IoSeek OTF2_GlobalEvtReaderCallback_IoSeek_callback;
  OTF2_GlobalEvtReaderCallback_IoChangeStatusFlags OTF2_GlobalEvtReaderCallback_IoChangeStatusFlags_callback;
  OTF2_GlobalEvtReaderCallback_IoDeleteFile OTF2_GlobalEvtReaderCallback_IoDeleteFile_callback;
  OTF2_GlobalEvtReaderCallback_IoOperationBegin OTF2_GlobalEvtReaderCallback_IoOperationBegin_callback;
  OTF2_GlobalEvtReaderCallback_IoOperationTest OTF2_GlobalEvtReaderCallback_IoOperationTest_callback;
  OTF2_GlobalEvtReaderCallback_IoOperationIssued OTF2_GlobalEvtReaderCallback_IoOperationIssued_callback;
  OTF2_GlobalEvtReaderCallback_IoOperationComplete OTF2_GlobalEvtReaderCallback_IoOperationComplete_callback;
  OTF2_GlobalEvtReaderCallback_IoOperationCancelled OTF2_GlobalEvtReaderCallback_IoOperationCancelled_callback;
  OTF2_GlobalEvtReaderCallback_IoAcquireLock OTF2_GlobalEvtReaderCallback_IoAcquireLock_callback;
  OTF2_GlobalEvtReaderCallback_IoReleaseLock OTF2_GlobalEvtReaderCallback_IoReleaseLock_callback;
  OTF2_GlobalEvtReaderCallback_IoTryLock OTF2_GlobalEvtReaderCallback_IoTryLock_callback;
  OTF2_GlobalEvtReaderCallback_ProgramBegin OTF2_GlobalEvtReaderCallback_ProgramBegin_callback;
  OTF2_GlobalEvtReaderCallback_ProgramEnd OTF2_GlobalEvtReaderCallback_ProgramEnd_callback;
  OTF2_GlobalEvtReaderCallback_NonBlockingCollectiveRequest OTF2_GlobalEvtReaderCallback_NonBlockingCollectiveRequest_callback;
  OTF2_GlobalEvtReaderCallback_NonBlockingCollectiveComplete OTF2_GlobalEvtReaderCallback_NonBlockingCollectiveComplete_callback;
  OTF2_GlobalEvtReaderCallback_CommCreate OTF2_GlobalEvtReaderCallback_CommCreate_callback;
  OTF2_GlobalEvtReaderCallback_CommDestroy OTF2_GlobalEvtReaderCallback_CommDestroy_callback;
};

struct OTF2_GlobalEvtReader_struct {
  struct OTF2_Reader_struct * otf2_reader;
  OTF2_GlobalEvtReaderCallbacks callbacks;
  void *user_data;
};

struct OTF2_Reader_struct {
  struct GlobalArchive *archive;

  OTF2_GlobalEvtReader* global_evt_reader;
  OTF2_GlobalDefReader* global_def_reader;

  int nb_locations;
  PALLAS(ThreadId)* locations;
  int *selected_locations;

  struct OTF2_EvtReader_struct *evt_readers;
  struct OTF2_DefReader_struct *def_readers;
  PALLAS(ThreadReader) **thread_readers;

};

#endif /* !OTF2_H */

/* -*-
   mode: c;
   c-file-style: "k&r";
   c-basic-offset 2;
   tab-width 2 ;
   indent-tabs-mode nil
   -*- */
